routes/web.php
<?php
/*
  ===============================================
  =        ANASAYFA YÖNLENDİRMELERİ            =
  ===============================================
*/
Route::get('/','HomeController@index')->name('anasayfa');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('makale/{slug}','PostController@postDetail')->name('post.detail');
Route::get('makaleler','PostController@index')->name('post.index');
Route::get('kategori/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('tag/{slug}','PostController@postByTag')->name('tag.posts');
Route::get('ara','PostController@search')->name('search');
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();

Route::group(['middleware' =>['auth']], function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');
});

/*
  ===============================================
  =     ADMİN YÖNETİM PANELİ YÖNLENDİRMELERİ    =
  ===============================================
*/

Route::group(['as'=>'admin.','prefix' => 'admin','namespace' => 'Admin', 'middleware' => ['auth','admin']],function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('tag','TagController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
    Route::put('/post/{id}/removeApprove','PostController@removeApprove')->name('post.removeApprove');
    Route::get('pending/post/','PostController@pending')->name('post.pending');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.delete');

    Route::get('authors','AuthorController@index')->name('author.index');
    Route::get('authors/{id}/','AuthorController@edit')->name('author.edit');
    Route::delete('authors/{id}','AuthorController@destroy')->name('author.destroy');

    /*
      ===============================================
      =  YAZAR YÖNETİM PANELİ YÖNLENDİRMELERİ      =
      ===============================================
    */
});
Route::group(['as' =>'author.','prefix' => 'author','namespace' => 'Author', 'middleware' => ['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');

});

resources/views/layouts/backend/partial/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="{{ url('storage/profile-pictures/'.Auth::user()->image)}}" width="48" height="48" alt="{{ Auth::user()->name }}" />
        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{Auth::user()->name}}</div>
            <div class="email">{{Auth::user()->email}}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">
                    <li>
                      @if (Auth::user()->role_id == 1)
                        <a href="{{ route('admin.settings')}}"><i class="material-icons">person</i>Profilim</a>
                      @elseif(Auth::user()->role_id = 2)
                        <a href="{{ route('author.settings')}}"><i class="material-icons">person</i>Profilim</a>
                      @endif
                    </li>
                    <li role="separator" class="divider"></li>
                    <li role="separator" class="divider"></li>
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>Çıkış
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">Ana Menü</li>
        @if(Request::is('admin*'))
            <li class="{{Request::is('admin/dashboard') ? 'active' : ''}}">
                <a href="{{ route('admin.dashboard') }}">
                    <i class="material-icons">home</i>
                    <span>Anasayfa</span>
                </a>
            </li>
             <li class="{{Request::is('admin/tag*') ? 'active' : ''}}">
                <a href="{{ route('admin.tag.index') }}">
                    <i class="material-icons">label</i>
                    <span>Etiketler</span>
                </a>
             </li>
             <li class="{{Request::is('admin/category*') ? 'active' : ''}}">
                <a href="{{ route('admin.category.index') }}">
                    <i class="material-icons">home</i>
                    <span>Kategoriler</span>
                </a>
             </li>
                <li class="{{Request::is('admin/post*') ? 'active' : ''}}">
                    <a href="{{ route('admin.post.index') }}">
                        <i class="material-icons">library_books</i>
                        <span>İçerikler</span>
                    </a>
                </li>
                <li class="{{Request::is('admin/comment*') ? 'active' : ''}}">
                    <a href="{{ route('admin.comment.index') }}">
                        <i class="material-icons">comment</i>
                        <span>Yorumlar</span>
                    </a>
                </li>
                <li class="{{Request::is('admin/pending/post') ? 'active' : ''}}">
                    <a href="{{ route('admin.post.pending') }}">
                        <i class="material-icons">send</i>
                        <span>Onay Bekleyen İçerikler</span>
                    </a>
                </li>
                <li class="{{Request::is('admin/favorite') ? 'active' : ''}}">
                    <a href="{{ route('admin.favorite.index') }}">
                        <i class="material-icons">favorite</i>
                        <span>Favori İçerikler</span>
                    </a>
                </li>
                <li class="{{Request::is('admin/authors') ? 'active' : ''}}">
                    <a href="{{ route('admin.author.index') }}">
                        <i class="material-icons">format_list_bulleted</i>
                        <span>Yazarlar</span>
                    </a>
                </li>
                <li class="{{Request::is('admin/subscriber') ? 'active' : ''}}">
                    <a href="{{ route('admin.subscriber.index') }}">
                        <i class="material-icons">mail</i>
                        <span>E-Posta Abonelikleri</span>
                    </a>
                </li>

            <li class="header">Sistem</li>
            <li class="divider" > </li>
            <li class="{{Request::is('admin/settings') ? 'active' : ''}}">
                <a href="{{ route('admin.settings') }}">
                    <i class="material-icons">settings</i>
                    <span>Ayarlar</span>
                </a>
            </li>
            <li>
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="material-icons">input</i>
                    <span>Çıkış</span>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        @endif

         @if(Request::is('author*'))
                <li class="{{Request::is('author/dashboard') ? 'active' : ''}}">
                    <a href="{{ route('author.dashboard') }}">
                        <i class="material-icons">home</i>
                        <span>Anasayfa</span>
                    </a>
                </li>
                <li class="{{Request::is('author/post*') ? 'active' : ''}}">
                    <a href="{{ route('author.post.index') }}">
                        <i class="material-icons">library_books</i>
                        <span>İçerikler</span>
                    </a>
                </li>
                <li class="{{Request::is('author/comment*') ? 'active' : ''}}">
                    <a href="{{ route('author.comment.index') }}">
                        <i class="material-icons">comment</i>
                        <span>Yorumlar</span>
                    </a>
                </li>
                <li class="{{Request::is('author/favorite') ? 'active' : ''}}">
                    <a href="{{ route('author.favorite.index') }}">
                        <i class="material-icons">favorite</i>
                        <span>Favori İçerikler</span>
                    </a>
                </li>
                <li class="header">Sistem</li>
                <li class="divider" > </li>
                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="material-icons">input</i>
                        <span>Çıkış</span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
         @endif

        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; {{date('Y')}} <a href="javascript:void(0);">Murat CAN </a>
        </div>
        <div class="version">
            <b>Versiyon: </b> 1.0
        </div>
    </div>
    <!-- #Footer -->
</aside>

resources/views/layouts/backend/partial/topbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ route('admin.dashboard') }}">Yönetim Paneli</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->
                <!-- Tasks -->
                <!-- #END# Tasks -->
                 </ul>
        </div>
    </div>
</nav>