routes/web.php
<?php
/*
  ===============================================
  =        ANASAYFA YÖNLENDİRMELERİ            =
  ===============================================
*/
Route::get('/','HomeController@index')->name('anasayfa');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('makale/{slug}','PostController@postDetail')->name('post.detail');
Route::get('makaleler','PostController@index')->name('post.index');
Route::get('kategori/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('tag/{slug}','PostController@postByTag')->name('tag.posts');
Route::get('ara','PostController@search')->name('search');
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();

Route::group(['middleware' =>['auth']], function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');
});

/*
  ===============================================
  =     ADMİN YÖNETİM PANELİ YÖNLENDİRMELERİ    =
  ===============================================
*/

Route::group(['as'=>'admin.','prefix' => 'admin','namespace' => 'Admin', 'middleware' => ['auth','admin']],function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('tag','TagController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
    Route::put('/post/{id}/removeApprove','PostController@removeApprove')->name('post.removeApprove');
    Route::get('pending/post/','PostController@pending')->name('post.pending');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.delete');

    Route::get('authors','AuthorController@index')->name('author.index');
    Route::get('authors/{id}/','AuthorController@edit')->name('author.edit');
    Route::delete('authors/{id}','AuthorController@destroy')->name('author.destroy');

    /*
      ===============================================
      =  YAZAR YÖNETİM PANELİ YÖNLENDİRMELERİ      =
      ===============================================
    */
});
Route::group(['as' =>'author.','prefix' => 'author','namespace' => 'Author', 'middleware' => ['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');

});

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\User;

class AuthorController extends Controller
{
    public function index(){
      $authors = User::authors();
      return view('admin.author.index',compact('authors'));
    }

    public function destroy($id){
        $author = User::find($id);
        $delete = $author->delete();

        if($delete){
          Toastr::success('Yazar başarıyla silindi.','Başarılı');
          return redirect()->back();
        }else{
          Toastr::error('Yazar silinirken bir hata oluştu.','Hata!');
          return redirect()->back();
        }
    }
}

app/Http/Controllers/Author/CommentController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

use App\Post;
use App\Comment;

class CommentController extends Controller
{
    public function index(){
       $posts = Auth::user()->posts;
       return view('author.comment.index', compact('posts'));

    }
    public function edit($id){
       $comment = Comment::find($id);
       return view('admin.comment.edit', compact('comment'));
    }

    public function update(Request $request, $id){
      $comment = Comment::find($id);

      $this->validate($request, array('comment' => 'required'));

      $comment->comment = $request->comment;
      $update = $comment->save();

      if($update){
        Toastr::success('Yorum Başarıyla Güncellendi','Başarılı!');
        return redirect()->route('admin.comment.index');
      }else{
        Toastr::error('Yorum Güncellenirken Bir Hata Oluştu.','Hata!');
        return redirect()->back();
      }

    }
    public function destroy($id){

        $comment = Comment::find($id);
        if ($comment->post->user->id == Auth::id())
        {
            $delete  = $comment->delete();

            if($delete){
              Toastr::success('Yorum Başarıyla Silindi.','Başarılı!');
              return redirect()->back();
            }else{
              Toastr::error('Yorum Silinirken Bir Hata Oluştu.','Hata!');
              return redirect()->back();
            }
        }
        else
        {
          Toastr::error('Bu Yorumu Silme Yetkiniz Bulunmamakta.','Hata!');
          return redirect()->back();
        }

    }
}

app/Http/Controllers/Author/DashboardController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\User;
class DashboardController extends Controller
{
    public function index(){
        $user  = Auth::user();
        $posts = $user->posts;
        $popular_posts = $user->posts()->withCount('comments')
          ->withCount('favorite_to_users')
          ->orderBy('comments_count','desc')
          ->orderBy('favorite_to_users_count','desc')
          ->take(5)
          ->get();
        $total_pending_posts = $posts->where('is_approved',false)->count();
        $total_views = $posts->sum('view_count');
        return view('author.dashboard',compact('posts','popular_posts','total_pending_posts','total_views'));
    }
}

app/Http/Controllers/Author/FavoriteController.php
<?php

namespace App\Http\Controllers\Author;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
class FavoriteController extends Controller
{
    public function index(){
      $posts = Auth::user()->favorite_posts;

      return view('author.favorite', compact('posts'));
    }
}

app/Http/Controllers/Author/PostController.php
<?php

namespace App\Http\Controllers\Author;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Notifications\NewAuthorPost;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Notification;
use Intervention\Image\Facades\Image;
use App\Post;
use App\Category;
use App\Tag;
use App\User;
class PostController extends Controller
{
    public function index()
    {
      $posts = Auth::user()->posts()->latest()->get();
      return view('author.post.index',compact('posts'));

    }
    public function create()
    {
      $categories = Category::all();
      $tags       = Tag::all();
      return view('author.post.create',compact('categories','tags'));
    }
    public function store(Request $request)
    {

        $this->validate(request(),array(
          'title'      => 'required|unique:posts',
          'body'       => 'required',
          'image'      => 'required|mimes:jpeg,jpg,png,gif',
          'categories' => 'required',
          'tags'       => 'required'
        ));

        $image = $request->file('image');
        $slug  = str_slug($request->title);

        if(isset($image))
        {
            $currentDate = Carbon::now()->toDateString();
            $imageName   = $slug."-".$currentDate."-".uniqid().'.'.$image->getClientOriginalExtension();

            if(!Storage::disk('public')->exists('post'))
            {
                Storage::disk('public')->makeDirectory('post');
            }

            $postImage = Image::make($image)->resize(1600,1066)->save();
            Storage::disk('public')->put('post/'.$imageName,$postImage);
        }
        else
        {
            $imageName = "default.png";
        }

        $post = new Post();
        $post->title = $request->title;
        $post->slug  = $slug;
        $post->body  = $request->body;
        $post->user_id = Auth::id();
        $post->image  = $imageName;

        if(isset($request->status))
        {
          $post->status = true;
        }
        else
        {
          $post->status = false;
        }

        $post->is_approved = false;

        $post->save();



        $post->categories()->attach($request->categories);
        $post->tags()->attach($request->tags);
        // send email notification to admin
        $users = User::where('role_id',1)->get();
        \Notification::send($users, new NewAuthorPost($post));

        Toastr::success('Kayıt Başarıyla Eklendi. Yönetici onayı bekleniyor..','Başarılı!');
        return redirect()->route('author.post.index');
    }
    public function show(Post $post)
    {
      if($post->user_id != Auth::id())
        {
          Toastr::error('Bu içeriğe erişim hakkınız yok.','HATA!');
          return redirect()->back();
        }

      return view('author.post.show',compact('post'));
    }
    public function edit(Post $post)
    {
      if($post->user_id != Auth::id())
      {
          Toastr::error('Bu içeriğe erişim hakkınız yok.','HATA!');
          return redirect()->back();
      }

      $categories = Category::all();
      $tags       = Tag::all();
      return view('author.post.edit',compact('categories','tags','post'));
    }

    public function update(Request $request, Post $post)
    {
      if($post->user_id != Auth::id())
      {
          Toastr::error('Bu içeriğe erişim hakkınız yok.','HATA!');
          return redirect()->back();
      }

      $this->validate(request(), array(
          'title'      => 'required',
          'body'       => 'required',
          'categories' => 'required',
          'tags'       => 'required'
        ));

        $slug = str_slug($request->title);
        $image = $request->file('image');

        if(isset($image)){
          $this->validate(request(),array(
            'image' => 'required|mimes:jpeg,png,jpg,gif'
        ));

          if(isValid('image'))
          {
             $currentDate = Carbon::now()->toDateString();
             $imageName   = $slug."-".$currentDate."-".uniqid().".".$image->getClientOriginalExtension();

             if(!Storage::disk('public')->exists('post')){
               Storage::disk('public')->makeDirectory('post');
             }
              // delete old image if exists
            if(Storage::disk('public')->exists('post/'.$post->image)){
              Storage::disk('public')->delete('post/'.$post->image);
            }

            $postImage = Image::make($image)->resize(1600,1066)->save();
            Storage::disk('public')->put('post/'.$imageName,$postImage);
          }

        }
        else
        {
          $imageName = $post->image;
        }

        $post->user_id = Auth::id();
        $post->title   = $request->title;
        $post->body    = $request->body;
        $post->slug    = $slug;
        $post->image   = $imageName;

        if(isset($request->status))
        {
          $post->status = true;
        }
        else
        {
          $post->status = false;
        }

        $post->is_approved = false;

        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        Toastr::success('Kayıt Başarıyla Güncellendi.','Başarılı!');
        return redirect()->route('author.post.index');
    }
    public function destroy(Post $post)
    {
        if($post->user_id != Auth::id())
        {
          Toastr::error('Bu içeriğe erişim hakkınız yok.','HATA!');
          return redirect()->back();
        }

        if(Storage::disk('public')->exists('post/'.$post->image))
        {
            Storage::disk('public')->delete('post/'.$post->image);
        }

        $post->categories()->detach();
        $post->tags()->detach();
        $post->delete();

        Toastr::success('Kayıt Silindi.','Kayıt Silindi');
        return redirect()->route('author.post.index');
    }
    public function updatePassword(){
        
    }
}

app/Http/Controllers/Author/SettingsController.php
<?php
namespace App\Http\Controllers\Author;
use App\User;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
class SettingsController extends Controller
{
  public function index()
  {
      return view('author.settings');
  }
  public function updateProfile(Request $request)
  {
      $this->validate($request,[
          'name' => 'required',
          'email' => 'required|email'
      ]);
      $image = $request->file('image');
      $slug = str_slug($request->name);
      $user = User::findOrFail(Auth::id());
      if (isset($image))
      {
          if($image->isValid()){

              $currentDate = Carbon::now()->toDateString();
              $imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
              if (!Storage::disk('public')->exists('profile-pictures'))
              {
               Storage::disk('public')->makeDirectory('profile-pictures');
              }
    //            Delete old image form profile folder
              if (Storage::disk('public')->exists('profile-pictures/'.$user->image))
              {
                  Storage::disk('public')->delete('profile-pictures/'.$user->image);
              }
              $profile = Image::make($image)->resize(500,500)->save();
              Storage::disk('public')->put('profile-pictures/'.$imageName,$profile);
            }
        }
        else
        {
            $imageName = $user->image;
        }
      $user->name = $request->name;
      $user->email = $request->email;
      $user->image = $imageName;
      $user->about = $request->about;
      $user->save();
      Toastr::success('Profiliniz başarıyla güncellendi.','Başarılı!');
      return redirect()->back();
  }
  public function updatePassword(Request $request)
  {
      $this->validate($request,[
          'old_password' => 'required',
          'password_confirmation' => 'required|same:new_password',
      ]);
      $hashedPassword = Auth::user()->password;
      if (Hash::check($request->old_password,$hashedPassword))
      {
          if (!Hash::check($request->new_password,$hashedPassword))
          {
              $user = User::find(Auth::id());
              $user->password = Hash::make($request->new_password);
              $user->save();
              Toastr::success('Şifreniz Başarıyla Güncellendi','Başarılı');
              Auth::logout();
              return redirect()->back();
          } else {
              Toastr::error('Yeni şifreniz eskisiyle aynı olamaz.','Hata!');
              return redirect()->back();
          }
      } else {
          Toastr::error('Şifreler eşleşmiyor.','Hata!');
          return redirect()->back();
      }
  }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
class AuthorController extends Controller
{
    public function profile($username){
      $author = User::where('username',$username)->first();
      $posts  = $author->posts()->approved()->published()->get();
      return view('profile', compact('author','posts'));
    }
}

resources/views/admin/author/create.blade.php
@extends('layouts.backend.app')

@section('title','Kategori Ekle')

@push('css')

@endpush

@section('content')
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Yeni Kategori Ekle

                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action = "{{ route('admin.category.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" name="name" class="form-control">
                                <label class="form-label">Kategori Adı</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="file" name="image">
                        </div>

                        <br>
                        <a href="{{ route('admin.category.index') }}" class="btn btn-danger m-t-15 waves-effect">İptal</a>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->
@endsection

@push('js')

@endpush

resources/views/admin/author/edit.blade.php
@extends('layouts.backend.app')

@section('title','Kategori Düzenle')

@push('css')

@endpush

@section('content')
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                         Kategori Düzenle

                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action = "{{ route('admin.category.update', $category->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label>Yüklü Görsel</label>
                            <img style="width:200px; height: 150px;"
                                 src="{{asset('category/'.$category->image)}}"
                                 alt="{{$category->name}}">
                        </div>
                        <div class="form-group">
                            <label> Yeni Resim Yükle</label>
                            <input type="file" name="image">
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" name="name" class="form-control" value="{{$category->name}}">
                                <label class="form-label">Etiket Adı</label>

                            </div>
                            @if($errors->has('name'))

                                {!! $errors->first('name', '<p class="">:message</p>') !!}
                            @endif
                        </div>

                        <br>
                        <a href="{{ route('admin.category.index') }}" class="btn btn-danger m-t-15 waves-effect">İptal</a>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->
@endsection

@push('js')

@endpush

resources/views/admin/author/index.blade.php
@extends('layouts.backend.app')

@section('title','Yazarlar')


@push('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        {{-- <div class="block-header">
            <a  class="btn btn-primary btn-lg waves-effect text-center" href="{{ route('admin.author.create')}}">
                <i class="material-icons" >add</i>Yeni Kayıt
            </a>
        </div> --}}
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Yazarlar
                            @if($authors->count() > 0)
                                <span class="bg-pink" style="padding: 5px">{{$authors->count()}}</span>
                            @endif
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                    @if($authors->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Profil Resmi</th>
                                        <th>Adı Soyadı</th>
                                        <th>Kullanıcı Adı</th>
                                        <th>Email Adresi</th>
                                        <th>İçerik Sayısı</th>
                                        <th>Yorum Sayısı </th>
                                        <th  class="text-center">İşlemler</th>

                                    </tr>
                                </thead>

                                <tbody>
                                @foreach($authors as $i => $author)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>
                                            <img style="width:100px; height: 80px;"
                                                src="{{asset('storage/profile-pictures/'.$author->image)}}"
                                                alt="{{asset($author->name)}}">
                                        </td>
                                        <td>{{ $author->name }}</td>
                                        <td>{{ $author->username }}</td>
                                        <td>{{$author->email}}</td>
                                        <td>{{$author->posts->count()}}</td>
                                        <td>{{$author->comments->count() }}</td>
                                        <td class="text-center">

                                            <button  class="btn btn-danger" type="button" onclick="deleteAuthor({{ $author->id  }})">
                                                <i class="material-icons">delete</i>

                                            </button>
                                            <form action="{{ route('admin.author.destroy',$author->id)}}" method="POST" id="delete-form-{{$author->id}}" style="display:none">
                                                @csrf
                                                @method('DELETE')


                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    @else
                            <div class="alert alert-warning">
                               Hiçbir kayıt bulunamadı. Yeni kayıt eklemek için  {{--<strong><a href="{{ route('admin.author.create') }}">buraya</a></strong> tıklayın. --}}
                            </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->

    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <script>
        function deleteAuthor(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Silmek istediğinize emin misiniz?',
                text: "Bilgiler kalıcı olarak silinecek!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Evet, sil!',
                cancelButtonText: 'Vazgeç!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                   event.preventDefault();
                   document.getElementById('delete-form-'+id).submit();

                }
            })
        }
    </script>
@endpush