routes/web.php
<?php
/*
  ===============================================
  =        ANASAYFA YÖNLENDİRMELERİ            =
  ===============================================
*/
Route::get('/','HomeController@index')->name('anasayfa');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('makale/{slug}','PostController@postDetail')->name('post.detail');
Route::get('makaleler','PostController@index')->name('post.index');
Route::get('kategori/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('tag/{slug}','PostController@postByTag')->name('tag.posts');
Route::get('ara','PostController@search')->name('search');
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();

Route::group(['middleware' =>['auth']], function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');
});

/*
  ===============================================
  =     ADMİN YÖNETİM PANELİ YÖNLENDİRMELERİ    =
  ===============================================
*/

Route::group(['as'=>'admin.','prefix' => 'admin','namespace' => 'Admin', 'middleware' => ['auth','admin']],function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('tag','TagController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
    Route::put('/post/{id}/removeApprove','PostController@removeApprove')->name('post.removeApprove');
    Route::get('pending/post/','PostController@pending')->name('post.pending');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.delete');

    Route::get('authors','AuthorController@index')->name('author.index');
    Route::get('authors/{id}/','AuthorController@edit')->name('author.edit');
    Route::delete('authors/{id}','AuthorController@destroy')->name('author.destroy');

    /*
      ===============================================
      =  YAZAR YÖNETİM PANELİ YÖNLENDİRMELERİ      =
      ===============================================
    */
});
Route::group(['as' =>'author.','prefix' => 'author','namespace' => 'Author', 'middleware' => ['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');

});

resources/views/admin/favorite.blade.php
@extends('layouts.backend.app')

@section('title','İçerikler')


@push('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">

        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Favori İçerikler
                            @if($posts->count() > 0)
                                <span class="bg-pink" style="padding: 5px">{{$posts->count()}}</span>
                            @endif
                        </h2>
                    </div>
                    <div class="body">
                    @if($posts->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Görsel</th>
                                        <th>Başlık</th>
                                        <th><i class="material-icons">visibility</i></th>
                                        <th><i class="material-icons">favorite</i></th>
                                        <th><i class="material-icons">comment</i>

                                        <th  class="text-center">İşlemler</th>

                                    </tr>
                                </thead>

                                <tbody>
                                @foreach($posts as $i => $post)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>
                                            <img style="width:150px; height: 150px;"
                                                src="{{url('storage/post/'.$post->image)}}"
                                                alt="{{asset($post->title)}}">
                                        </td>
                                        <td>{{ $post->title }}</td>
                                        <td>{{$post->view_count}}</td>
                                        <td>
                                              {{ $post->favorite_to_users->count() <= 0 ? "0":$post->favorite_to_users->count()}}
                                        </td>
                                        <td>
                                              0
                                        </td>
                                        <td class="text-center">

                                            <a class="btn btn-warning success btn-block" href="{{ route('admin.post.show',$post->id) }}"><i class="material-icons">visibility</i></a>
                                            <button  class="btn btn-danger btn-block" type="button" onclick="removePost({{ $post->id  }})">
                                                <i class="material-icons">delete</i>

                                            </button>
                                            <form action="{{ route('post.favorite',$post->id)}}" method="POST" id="remove-form-{{$post->id}}" style="display:none">
                                                @csrf
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    @else
                            <div class="alert alert-warning">
                                Favorilerinizde herhangi bir içerik bulunamadı.
                            </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->

    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script>
        function removePost(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Favorilerinizden kaldırmak istediğinize emin misiniz?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Evet, kaldır!',
                cancelButtonText: 'Vazgeç!',
                reverseButtons: false
            }).then((result) => {
                if (result.value) {
                   event.preventDefault();
                   document.getElementById('remove-form-'+id).submit();

                }
            })
        }
    </script>
@endpush

resources/views/admin/settings.blade.php
@extends('layouts.backend.app')

@section('title','Ayarlar')

@push('css')

@endpush

@section('content')
  <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Profil
                            </h2>

                              @if($errors->any())
                                <div class="alert bg-pink">
                                @foreach ($errors->all() as $error)
                                    <li>{{$error}}</li>
                                @endforeach

                              </div>
                              @endif
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>
                                        <li><a href="javascript:void(0);" class=" waves-effect waves-block">Another action</a></li>
                                        <li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#profile_with_icon_title" data-toggle="tab">
                                        <i class="material-icons">face</i> Profil
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#change_password_with_icon_title" data-toggle="tab">
                                        <i class="material-icons">vpn_key</i> Şifre
                                    </a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">

                                <div role="tabpanel" class="tab-pane fade in active" id="profile_with_icon_title">

                                <form class="form-horizontal" method="POST" action="{{ route('admin.update.profile') }}" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="name" style="margin-top:75px">Profil Resmi</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                    <img src="{{ url('storage/profile-pictures/'.Auth::user()->image )}}" alt="{{ Auth::user()->name }}"
                                                         style="width:150px; height:150px; border-radius:50%;">
                                            </div>
                                        </div>
                                    </div><br><br>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="">Profil Resmini Değiştir</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                      <input type="file" name="image" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="name">Ad Soyad</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" id="name" name="name" class="form-control" placeholder="Örn: John DOE"
                                                           value="{{ Auth::user()->name }}">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="email_address_2">Email Address</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <input type="text" id="email_address_2" class="form-control" name="email" placeholder="Örn: johndoe@blog.com"
                                                           value="{{ Auth::user()->email }}">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                            <label for="name">Hakkımda</label>
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                            <div class="form-group">
                                                <div class="form-line">
                                                    <textarea type="text" id="tinymce" name="about" class="form-control" placeholder="Örn: John DOE">
                                                           {{ Auth::user()->about }}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row clearfix">
                                        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Güncelle</button>
                                        </div>
                                    </div>
                                </form>

                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="change_password_with_icon_title">
                                  <form class="form-horizontal" method="POST" action="{{ route('admin.update.password') }}">
                                      @csrf
                                      @method('PUT')

                                      <div class="row clearfix">
                                          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                              <label for="old_password">Mevcut Şifre</label>
                                          </div>
                                          <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                              <div class="form-group">
                                                  <div class="form-line">
                                                      <input type="password" id="old_password" name="old_password" class="form-control">
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="row clearfix">
                                          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                              <label for="new_password">Yeni Şifre</label>
                                          </div>
                                          <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                              <div class="form-group">
                                                  <div class="form-line">
                                                      <input type="password" id="new_password" name="new_password" class="form-control">
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="row clearfix">
                                          <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                              <label for="password_confirmation">Yeni Şifre (Tekrar)</label>
                                          </div>
                                          <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                              <div class="form-group">
                                                  <div class="form-line">
                                                      <input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="row clearfix">
                                          <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                              <button type="submit" class="btn btn-primary m-t-15 waves-effect">Güncelle</button>
                                          </div>
                                      </div>
                                  </form>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

@push('js')
  <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>
  <script>
      $(function () {
          //TinyMCE
          tinymce.init({
              selector: "textarea#tinymce",
              theme: "modern",
              height: 300,
              plugins: [
                  'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                  'searchreplace wordcount visualblocks visualchars code fullscreen',
                  'insertdatetime media nonbreaking save table contextmenu directionality',
                  'emoticons template paste textcolor colorpicker textpattern imagetools'
              ],
              toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
              toolbar2: 'print preview media | forecolor backcolor emoticons',
              image_advtab: true
          });
          tinymce.suffix = ".min";
          tinyMCE.baseURL = '{{asset('assets/backend/plugins/tinymce')}}';
      });
  </script>
@endpush

resources/views/admin/subscriber.blade.php
@extends('layouts.backend.app')

@section('title','E-Posta Aboneleri')


@push('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Kategoriler
                            @if($subscribers->count() > 0)
                                <span class="bg-pink" style="padding: 5px">{{$subscribers->count()}}</span>
                            @endif
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                    @if($subscribers->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>E-Posta</th>
                                        <th>Abonelik Tarihi</th>
                                        <th  class="text-center">İşlemler</th>

                                    </tr>
                                </thead>

                                <tbody>
                                @foreach($subscribers as $i => $subscriber)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>{{ $subscriber->email }}</td>
                                        <td>{{ date('d/m/Y',strtotime($subscriber->created_at)) }}</td>

                                        <td class="text-center">
                                            <button  class="btn btn-danger" type="button" onclick="deleteSubscriber({{ $subscriber->id  }})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form action="{{ route('admin.subscriber.delete',$subscriber->id)}}" method="POST" id="delete-form-{{$subscriber->id}}" style="display:none">
                                                @csrf
                                                @method('DELETE')


                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    @else
                            <div class="alert alert-warning">
                               Hiçbir kayıt bulunamadı.
                            </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->

    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <script>
        function deleteSubscriber(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Silmek istediğinize emin misiniz?',
                text: "Bilgiler kalıcı olarak silinecek!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Evet, sil!',
                cancelButtonText: 'Vazgeç!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                   event.preventDefault();
                   document.getElementById('delete-form-'+id).submit();

                }
            })
        }
    </script>
@endpush