routes/web.php
<?php
/*
  ===============================================
  =        ANASAYFA YÖNLENDİRMELERİ            =
  ===============================================
*/
Route::get('/','HomeController@index')->name('anasayfa');

Route::post('subscriber','SubscriberController@store')->name('subscriber.store');
Route::get('makale/{slug}','PostController@postDetail')->name('post.detail');
Route::get('makaleler','PostController@index')->name('post.index');
Route::get('kategori/{slug}','PostController@postByCategory')->name('category.posts');
Route::get('tag/{slug}','PostController@postByTag')->name('tag.posts');
Route::get('ara','PostController@search')->name('search');
Route::get('profile/{username}','AuthorController@profile')->name('author.profile');


Auth::routes();

Route::group(['middleware' =>['auth']], function(){
    Route::post('favorite/{post}/add','FavoriteController@add')->name('post.favorite');
    Route::post('comment/{post}','CommentController@store')->name('comment.store');
});

/*
  ===============================================
  =     ADMİN YÖNETİM PANELİ YÖNLENDİRMELERİ    =
  ===============================================
*/

Route::group(['as'=>'admin.','prefix' => 'admin','namespace' => 'Admin', 'middleware' => ['auth','admin']],function(){
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('tag','TagController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::put('/post/{id}/approve','PostController@approval')->name('post.approve');
    Route::put('/post/{id}/removeApprove','PostController@removeApprove')->name('post.removeApprove');
    Route::get('pending/post/','PostController@pending')->name('post.pending');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');
    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('/subscriber','SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{id}', 'SubscriberController@destroy')->name('subscriber.delete');

    Route::get('authors','AuthorController@index')->name('author.index');
    Route::get('authors/{id}/','AuthorController@edit')->name('author.edit');
    Route::delete('authors/{id}','AuthorController@destroy')->name('author.destroy');

    /*
      ===============================================
      =  YAZAR YÖNETİM PANELİ YÖNLENDİRMELERİ      =
      ===============================================
    */
});
Route::group(['as' =>'author.','prefix' => 'author','namespace' => 'Author', 'middleware' => ['auth','author']],function(){
    Route::get('dashboard','DashboardController@index')->name('dashboard');

    Route::resource('post','PostController');
    Route::resource('comment','CommentController');

    Route::get('/favorite','FavoriteController@index')->name('favorite.index');

    Route::get('settings','SettingsController@index')->name('settings');
    Route::put('update-settings','SettingsController@updateProfile')->name('update.profile');
    Route::put('update-password','SettingsController@updatePassword')->name('update.password');

});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
   public function posts(){
       return $this->belongsToMany('App\Post')->withTimestamps();
   }


}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Tag;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{

    public function index()
    {
        $tags = Tag::all();

        return view('admin.tag.index', compact('tags'));
    }

    public function create()
    {
        return view('admin.tag.create');
    }


    public function store(Request $request)
    {
        $this->validate(request(), array(
            'name' => 'required'
        ));

        $tag = new Tag();
        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);

        $insert = $tag->save();

        if ($insert) {
            Toastr::success('Kayıt başarıyla eklendi.', 'Başarılı!');
            return redirect()->route('admin.tag.index');
        } else {
            Toastr::error('Kayıt eklenirken bir sorun oluştu.', 'Hata!');
            return route()->back();
        }

    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $tag = Tag::find($id);

        return view('admin.tag.edit', compact('tag'));
    }


    public function update(Request $request, $id)
    {
        $this->validate(request(), array(
            'name' => 'required'
        ));
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->slug = str_slug($request->name);

        $update = $tag->save();
        if ($update) {
            Toastr::success('Kayıt başarıyla güncellendi.', 'Başarılı!');
            return redirect()->route('admin.tag.index');
        } else {
            Toastr::error('Kayıt güncellenirken bir sorun oluştu.', 'Hata!');
            return route()->back();
        }

    }


    public function destroy($id)
    {
        Tag::find($id)->delete();
        Toastr::success('Kayıt Silindi.', 'Başarılı!');
        return redirect()->back();


    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.backend.app')

@section('title','Etiket Ekle')

@push('css')

@endpush

@section('content')
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Yeni Etiket Ekle

                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action = "{{ route('admin.tag.store') }}" method="POST">
                        @csrf
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" name="name" class="form-control">
                                <label class="form-label">Etiket Adı</label>
                            </div>
                        </div>

                        <br>
                        <a href="{{ route('admin.tag.index') }}" class="btn btn-danger m-t-15 waves-effect">İptal</a>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->
@endsection

@push('js')

@endpush

resources/views/admin/tag/edit.blade.php
@extends('layouts.backend.app')

@section('title','Etiket Düzenle')

@push('css')

@endpush

@section('content')
    <!-- Vertical Layout | With Floating Label -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                         Etiket Düzenle

                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action = "{{ route('admin.tag.update', $tag->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="name" name="name" class="form-control" value="{{$tag->name}}">
                                <label class="form-label">Etiket Adı</label>

                            </div>
                            @if($errors->has('name'))

                                {!! $errors->first('name', '<p class="">:message</p>') !!}
                            @endif
                        </div>

                        <br>
                        <a href="{{ route('admin.tag.index') }}" class="btn btn-danger m-t-15 waves-effect">İptal</a>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Kaydet</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Vertical Layout | With Floating Label -->
@endsection

@push('js')

@endpush

resources/views/admin/tag/index.blade.php
@extends('layouts.backend.app')

@section('title','Etiketler')


@push('css')

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <a  class="btn btn-primary btn-lg waves-effect text-center" href="{{ route('admin.tag.create')}}">
                <i class="material-icons" >add</i>Yeni Kayıt
            </a>
        </div>
        <!-- Exportable Table -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Kategoriler
                            @if($tags->count() > 0)
                                <span class="bg-pink" style="padding: 5px">{{$tags->count()}}</span>
                            @endif
                        </h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                    @if($tags->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Etiket Adı</th>
                                        <th>Slug</th>
                                        <th>İçerik Sayısı</th>
                                        <th  class="text-center">İşlemler</th>

                                    </tr>
                                </thead>

                                <tbody>
                                @foreach($tags as $i => $tag)
                                    <tr>
                                        <td>{{$i+1}}</td>
                                        <td>{{ $tag->name }}</td>
                                        <td>{{$tag->slug}}</td>
                                        <td>{{$tag->posts->count()}}</td>
                                        <td class="text-center">
                                            <a class="btn btn-success " href="{{route('admin.tag.edit',$tag->id)}}" >Düzenle</a>
                                            <button  class="btn btn-danger" type="button" onclick="deleteTag({{ $tag->id  }})">
                                                <i class="material-icons">delete</i>

                                            </button>
                                            <form action="{{ route('admin.tag.destroy',$tag->id)}}" method="POST" id="delete-form-{{$tag->id}}" style="display:none">
                                                @csrf
                                                @method('DELETE')


                                            </form>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>
                    @else
                            <div class="alert alert-warning">
                               Hiçbir kayıt bulunamadı. Yeni kayıt eklemek için  <strong><a href="{{ route('admin.tag.create') }}">buraya</a></strong> tıklayın.
                            </div>
                    @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Exportable Table -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->

    <script src="{{ asset('assets/backend/js/pages/tables/jquery-datatable.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

    <script>
        function deleteTag(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false,
            })

            swalWithBootstrapButtons.fire({
                title: 'Silmek istediğinize emin misiniz?',
                text: "Bilgiler kalıcı olarak silinecek!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Evet, sil!',
                cancelButtonText: 'Vazgeç!',
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                   event.preventDefault();
                   document.getElementById('delete-form-'+id).submit();

                }
            })
        }
    </script>
@endpush